[project]
name = "Python-HTML-Tutorial"
description = "An HTML tutorial where the exercises need to be solved in Python."
authors = [
    { name = "Sebastian Hungerecker" },
    { name = "Amen Ellah Kerimi" },
    { name = "Granth J" },
    { name = "Mohammad Mohsen" },
    { name = "Owen Wang" },
]
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
# This `dev` group contains all the development requirements for our linting toolchain.
# Don't forget to pin your dependencies!
# This list will have to be migrated if you wish to use another dependency manager.
dev = ["pre-commit~=4.2.0", "ruff~=0.12.2"]

[tool.ruff]
# Increase the line length. This breaks PEP8 but it is way easier to work with.
# The original reason for this limit was a standard vim terminal is only 79 characters,
# but this doesn't really apply anymore.
line-length = 119
# Target Python 3.12. If you decide to use a different version of Python
# you will need to update this value.
target-version = "py312"
# Automatically fix auto-fixable issues.
fix = true
# The directory containing the source code. If you choose a different project layout
# you will need to update this value.
src = ["src"]

[tool.ruff.lint]
# Enable all linting rules.
select = ["ALL"]
# Ignore some of the most obnoxious linting errors.
ignore = [
    # Missing docstrings.
    "D100",
    "D104",
    "D105",
    "D106",
    "D107",
    # Docstring whitespace.
    "D203",
    "D213",
    # Docstring punctuation.
    "D415",
    # Docstring quotes.
    "D301",
    # Builtins.
    "A",
    # Print statements.
    "T20",
    # TODOs.
    "TD002",
    "TD003",
    "FIX",
    # Insecure functions (we want to use eval and exec)
    "S102",
    "S307",
    "SIM108", # Don't force ternary
    "S314", # Don't force defusedxml parse
    "BLE001", # Don't enforce "no catchall"
    "PLR0911", # too many return
    "PLR0912",  # too many branches
    "C901",  # too complex (?? wtf why is this a thing)
]

[tool.pyright]
# Pyright can't resolve the PyScript modules because they don't actually exist in the Python environment
reportMissingImports = false
